name: Demo to create automatic PR

on:
  push:
    branches:
      - part-4

jobs:
  updateAuthor:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Extract git commit data
        uses: rlespinasse/git-commit-data-action@v1.5.0

      - name: Get latest commit message
        id: get-commit-message
        run: echo "::set-output name=message::$(git log -1 --pretty=%B)"

      - name: Create Pull Request
        id: create-pr
        uses: peter-evans/create-pull-request@v6
        with:
          branch: "part-4"
          base: main
          title: ${{ steps.get-commit-message.outputs.message }}
          committer: Atik203 <${{ env.GIT_COMMIT_AUTHOR_EMAIL }}>
          author: Atik203 <${{ env.GIT_COMMIT_AUTHOR_EMAIL }}>
          token: ${{ secrets.GH_TOKEN }}
          delete-branch: false

      - name: Approve Pull Request
        uses: juliangruber/approve-pull-request-action@v2
        with:
          github-token: ${{ secrets.GH_TOKEN }}
          number: ${{ steps.create-pr.outputs.pull-request-number }}

      - name: Merge Pull Request
        uses: juliangruber/merge-pull-request-action@v1.3.0
        with:
          github-token: ${{ secrets.GH_TOKEN }}
          number: ${{ steps.create-pr.outputs.pull-request-number }}
          method: squash
